services:
  app:
    build: .
    container_name: app-saego-pos
    hostname: saego-pos
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    networks:
      - production
networks:
  production:
